/*
 * 将所有mutations的函数名放在这个文件里
 */

export const SET_DEFAULTADDRESS = 'SET_DEFAULTADDRESS';
export const SET_SCENERYID = 'SET_SCENERYID';
export const SET_SHOPPINGCART = 'SET_SHOPPINGCART';
export const ADD_SHOPPINGCART = 'ADD_SHOPPINGCART';
export const REDUCE_SHOPPINGCART = 'REDUCE_SHOPPINGCART';
export const EMPTY_SHOPPINGCART = 'EMPTY_SHOPPINGCART';
